sudo: false
language: python
install:
  - pip install -U setuptools pip
  # We need this until the pkg_resources statement in setup.py is pushed into
  # a downstream patch.
  - pip install sqlalchemy jinja2
  - pip install tox
script:
  - tox

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=lint
    - TOXENV=docs
    - TOXENV: py27
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
